# Generated by Django 4.1.7 on 2023-06-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faq_type_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='type_faq',
        ),
    ]
