# Generated by Django 4.1.7 on 2024-11-01 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_us',
            old_name='addr',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='tel',
        ),
    ]
