# Generated by Django 4.1.7 on 2023-03-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='addr',
            field=models.TextField(verbose_name='ادرس'),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='desc',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='image',
            field=models.ImageField(upload_to='1.png', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='tel',
            field=models.CharField(max_length=150, verbose_name='تلفن'),
        ),
    ]
