# Generated by Django 4.1.7 on 2024-11-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_rename_addr_about_us_body_remove_about_us_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='body',
            field=models.TextField(verbose_name='متن'),
        ),
    ]
