# Generated by Django 4.1.7 on 2023-03-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="شماره تماس"
                    ),
                ),
                ("code", models.PositiveSmallIntegerField(verbose_name="کد")),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="زمان ساخت"),
                ),
            ],
            options={
                "verbose_name": "کد اعتبارسنجی",
                "verbose_name_plural": "کدهای اعتبارسنجی",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="ایمیل"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="شماره تماس"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال / غیرفعال"),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False, verbose_name="ادمین هست / ادمین نیست"
                    ),
                ),
            ],
            options={
                "verbose_name": "حساب کاربری",
                "verbose_name_plural": "حساب های کاربری",
            },
        ),
    ]
