# Generated by Django 4.1.7 on 2023-03-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="نام و نام خانوادگی"
            ),
        ),
    ]
