# Generated by Django 4.1.7 on 2024-10-30 08:20

from django.db import migrations, models
import top_projects.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=255, verbose_name='نام مهندس')),
                ('project_name', models.CharField(max_length=255, verbose_name='نام پروژه')),
                ('body', models.TextField(verbose_name='توضیحاتی درباره پروژه')),
                ('images_1', models.ImageField(upload_to=top_projects.utils.upload_image_top_project, verbose_name='تصویر شماره 1')),
                ('images_2', models.ImageField(upload_to=top_projects.utils.upload_image_top_project, verbose_name='تصویر شماره 2')),
                ('images_3', models.ImageField(upload_to=top_projects.utils.upload_image_top_project, verbose_name='تصویر شماره 3')),
                ('images_4', models.ImageField(upload_to=top_projects.utils.upload_image_top_project, verbose_name='تصویر شماره 4')),
                ('images_5', models.ImageField(upload_to=top_projects.utils.upload_image_top_project, verbose_name='تصویر شماره 5')),
                ('status', models.CharField(choices=[('A', 'پیگیری شده'), ('B', 'پیگیره نشده')], default='A', max_length=2, verbose_name='وضعیت درخواست')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='زمان ساخت')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه های برتر',
            },
        ),
    ]
