# Generated by Django 4.1.7 on 2023-03-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topproject',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='ادرس'),
        ),
    ]
