# Generated by Django 4.1.7 on 2023-03-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone_num', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('body', models.TextField(verbose_name='متن')),
                ('status', models.CharField(blank=True, choices=[('A', 'نشان داده شود'), ('B', 'نشان داده نشود')], max_length=2, null=True, verbose_name='ضعیت')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='زمان ساخت')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس با ما',
            },
        ),
    ]
