# Generated by Django 4.1.7 on 2023-03-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='شماره موبایل'),
        ),
    ]
