# Generated by Django 4.1.7 on 2023-03-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_remove_contactus_phone_num_contactus_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'نشان داده شود'), ('B', 'نشان داده نشود')], default='B', max_length=2, null=True, verbose_name='ضعیت'),
        ),
    ]
