# Generated by Django 4.1.7 on 2024-10-30 08:20

import content.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, null=True, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='ادرس')),
                ('status', models.CharField(blank=True, choices=[('A', 'نشان داده شود'), ('B', 'نشان داده نشود')], max_length=2, null=True, verbose_name='ضعیت')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='زمان ساخت')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='عنوان محتوا')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='ادرس')),
                ('body', models.TextField(verbose_name='متن')),
                ('cover', models.ImageField(upload_to=content.utils.upload_image_content, verbose_name='تصویر بزرگ')),
                ('thumbnail', models.ImageField(upload_to=content.utils.upload_image_content, verbose_name='تصویر بندانگشتی')),
                ('status', models.CharField(choices=[('A', 'نشان داده شود'), ('B', 'نشان داده نشود')], max_length=2, verbose_name='ضعیت')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='زمان ساخت')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='content.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محتوا',
                'verbose_name_plural': 'محتوا ها',
            },
        ),
    ]
