# Generated by Django 4.1.7 on 2023-05-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_content', models.CharField(blank=True, choices=[('A', 'UPVC (یو پی وی سی)'), ('B', ' آلومینیوم ترمال بریک'), ('C', ' شیشه نما')], max_length=2, null=True, verbose_name='نوع محتوا')),
                ('title', models.CharField(max_length=225, null=True, verbose_name='عنوان محتوا')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='ادرس')),
                ('body', models.TextField(verbose_name='متن')),
                ('status', models.CharField(blank=True, choices=[('A', 'نشان داده شود'), ('B', 'نشان داده نشود')], max_length=2, null=True, verbose_name='ضعیت')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='زمان ساخت')),
            ],
            options={
                'verbose_name': 'محتوا',
                'verbose_name_plural': 'محتوا ها',
            },
        ),
    ]
