# Generated by Django 4.1.7 on 2023-03-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='ادرس'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=225, null=True, verbose_name='عنوان محتوا'),
        ),
    ]
