# Generated by Django 4.1.7 on 2023-05-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='content',
            name='thumnail',
        ),
    ]
