# Generated by Django 4.1.7 on 2024-10-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='cover',
            field=models.ImageField(default='1.png', upload_to='', verbose_name='تصویر بزرگ'),
        ),
        migrations.AddField(
            model_name='content',
            name='thumnail',
            field=models.ImageField(default='1.png', upload_to='', verbose_name='تصویر بندانگشتی'),
        ),
    ]
