# Generated by Django 4.1.7 on 2023-03-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_slug_alter_content_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created',
            field=models.DateField(auto_now=True, verbose_name='زمان ساخت'),
        ),
    ]
