# Generated by Django 4.1.7 on 2024-10-26 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_cover_content_thumnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, null=True, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='ادرس')),
                ('status', models.CharField(blank=True, choices=[('A', 'نشان داده شود'), ('B', 'نشان داده نشود')], max_length=2, null=True, verbose_name='ضعیت')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='زمان ساخت')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='content.category', verbose_name='دسته بندی'),
        ),
    ]
