# Generated by Django 4.1.7 on 2023-03-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_content_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ساخت'),
        ),
    ]
