# Generated by Django 4.1.7 on 2024-10-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_content_thumnail_content_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='type_content',
        ),
    ]
