# Generated by Django 4.1.7 on 2023-03-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_content_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type_content',
            field=models.CharField(blank=True, choices=[('A', 'UPVC (یو پی وی سی)'), ('B', ' آلومینیوم ترمال بریک'), ('C', ' شیشه نما')], max_length=2, null=True, verbose_name='نوع محتوا'),
        ),
    ]
