# Generated by Django 4.1.7 on 2024-10-30 07:49

import content.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_content_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='cover',
            field=models.ImageField(upload_to=content.utils.upload_image_content, verbose_name='تصویر بزرگ'),
        ),
        migrations.AlterField(
            model_name='content',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=content.utils.upload_image_content, verbose_name='تصویر بندانگشتی'),
        ),
    ]
