# Generated by Django 4.1.7 on 2023-03-09 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام پنجره")),
            ],
            options={
                "verbose_name": "نوع پنجره",
                "verbose_name_plural": "نوع پنجره ها",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.FloatField(verbose_name="تعداد واحد")),
                ("number_units", models.FloatField(verbose_name=" units تعداد")),
                ("addr", models.TextField(verbose_name="ادرس محل")),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="زمان ساخت"),
                ),
                (
                    "name_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_name_user",
                        to="accounts.user",
                        verbose_name="نام و نام خانوادگی",
                    ),
                ),
                (
                    "phone_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_phone_number",
                        to="accounts.user",
                        verbose_name="شماره موبایل",
                    ),
                ),
                (
                    "type_window",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="order.typewindow",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست",
                "verbose_name_plural": "درخواست ها",
            },
        ),
    ]
