# Generated by Django 4.1.7 on 2023-04-16 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام پنجره')),
            ],
            options={
                'verbose_name': 'نوع پنجره',
                'verbose_name_plural': 'نوع پنجره ها',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_project', models.CharField(choices=[('A', 'نوساز'), ('B', 'بازسازی')], max_length=2, null=True, verbose_name='نوع پروژه ')),
                ('number', models.FloatField(max_length=1000, null=True, verbose_name='تعداد واحد ')),
                ('phone_number', models.CharField(max_length=11, null=True, unique=True, verbose_name='شماره تماس')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='نام و نام خانوادگی ')),
                ('citys', models.CharField(choices=[('1', 'آذربایجان شرقی'), ('2', 'آذربایجان غربی'), ('3', 'اردبیل'), ('4', 'اصفهان'), ('5', 'البرز'), ('6', 'ایلام'), ('7', 'بوشهر'), ('8', 'تهران'), ('9', 'چهارمحال و بختیاری'), ('10', 'خراسان جنوبی'), ('11', 'خراسان رضوی'), ('12', 'خراسان شمالی'), ('13', 'خوزستان'), ('14', 'زنجان'), ('15', 'سمنان'), ('16', 'سیستان و بلوچستان,'), ('17', 'فارس'), ('18', 'قزوین'), ('19', 'قم'), ('20', 'کردستان'), ('21', 'کرمان'), ('22', 'کرمانشاه'), ('23', 'کهگیلویه و بویراحمد'), ('24', 'گلستان'), ('25', 'لرستان'), ('26', 'گیلان'), ('27', 'مازندران'), ('28', 'مرکزی'), ('29', 'هرمزگان'), ('30', 'همدان'), ('31', 'یزد')], max_length=2, null=True, verbose_name='شهر')),
                ('status', models.CharField(blank=True, choices=[('A', 'پیگیری شده'), ('B', 'پیگیره نشده')], default='B', max_length=2, null=True, verbose_name='وضعیت درخواست')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='زمان ساخت')),
                ('type_window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.typewindow', verbose_name='نوع پنجره')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست ها',
            },
        ),
    ]
