# Generated by Django 4.1.7 on 2023-03-17 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام پنجره')),
            ],
            options={
                'verbose_name': 'نوع پنجره',
                'verbose_name_plural': 'نوع پنجره ها',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_project', models.CharField(choices=[('A', 'نوساز'), ('B', 'بازسازی')], max_length=2, null=True, verbose_name='نوع پروژه ')),
                ('number', models.FloatField(max_length=1000, null=True, verbose_name='تعداد واحد ')),
                ('phone_number', models.CharField(max_length=11, null=True, unique=True, verbose_name='شماره تماس')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='نام و نام خانوادگی ')),
                ('status', models.CharField(blank=True, choices=[('A', 'پیگیری شده'), ('B', 'پیگیره نشده')], default='B', max_length=2, null=True, verbose_name='وضعیت درخواست')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='زمان ساخت')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='common.city', verbose_name='شهر')),
                ('type_window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.typewindow', verbose_name='نوع پنجره')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست ها',
            },
        ),
    ]
