# Generated by Django 4.1.7 on 2023-03-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="name_user",
        ),
        migrations.AddField(
            model_name="order",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="نام و نام خانوادگی"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                unique=True,
                verbose_name="شماره تماس",
            ),
        ),
    ]
