# Generated by Django 4.1.7 on 2023-04-07 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='citys',
        ),
    ]
