# Generated by Django 4.1.7 on 2023-03-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lat',
            field=models.TextField(null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='order',
            name='long',
            field=models.TextField(null=True, verbose_name='longitude'),
        ),
    ]
