# Generated by Django 4.1.7 on 2023-03-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_lat_order_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'پیگیری شده'), ('B', 'پیگیره نشده')], default='B', max_length=2, null=True, verbose_name='وضعیت درخواست'),
        ),
    ]
