# Generated by Django 4.1.7 on 2023-03-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number_units',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.FloatField(blank=True, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='addr',
            field=models.TextField(blank=True, null=True, verbose_name='ادرس محل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.FloatField(blank=True, null=True, verbose_name='تعداد واحد'),
        ),
    ]
