# Generated by Django 4.1.7 on 2023-03-17 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_number_units_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.typewindow', verbose_name='نوع پنجره'),
        ),
    ]
