# Generated by Django 4.1.7 on 2023-03-17 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_type_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.typewindow', verbose_name='نوع پنجره *'),
        ),
    ]
