# Generated by Django 4.1.7 on 2023-03-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_type_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='addr',
            field=models.TextField(blank=True, null=True, verbose_name='ادرس محل '),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.FloatField(blank=True, null=True, verbose_name='شهر *'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام و نام خانوادگی *'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.FloatField(blank=True, null=True, verbose_name='تعداد واحد *'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='شماره تماس *'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_project',
            field=models.CharField(blank=True, choices=[('A', 'نوساز'), ('B', 'بازسازی')], max_length=2, null=True, verbose_name='نوع پروژه *'),
        ),
    ]
