# Generated by Django 4.1.7 on 2023-03-17 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_addr_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='addr',
            field=models.TextField(verbose_name='ادرس محل '),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='شهر '),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=100, null=True, verbose_name='نام و نام خانوادگی '),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.FloatField(max_length=1000, null=True, verbose_name='تعداد واحد '),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_project',
            field=models.CharField(choices=[('A', 'نوساز'), ('B', 'بازسازی')], max_length=2, null=True, verbose_name='نوع پروژه '),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.typewindow', verbose_name='نوع پنجره'),
        ),
    ]
