# Generated by Django 4.1.7 on 2023-03-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_addr_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='addr',
            field=models.TextField(blank=True, null=True, verbose_name='ادرس محل '),
        ),
    ]
