# Generated by Django 4.1.7 on 2023-03-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_lat_alter_order_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='long',
        ),
    ]
