# Generated by Django 4.1.7 on 2023-03-17 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('order', '0017_remove_order_addr_remove_order_lat_remove_order_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='common.city', verbose_name='شهر'),
        ),
    ]
